/* XPM */
static char *Blender_m[] = {
/* columns rows colors chars-per-pixel */
"32 26 113 2 ",
"   c None",
".  c #EA7400",
"X  c #EA7500",
"o  c #EA7600",
"O  c #EA7601",
"+  c #EA7702",
"@  c #EA7703",
"#  c #EA7804",
"$  c #EA7906",
"%  c #EB7B09",
"&  c #EB7B0A",
"*  c #EB7C0B",
"=  c #EB7C0C",
"-  c #EB7D0C",
";  c #EB7E0F",
":  c #EC8115",
">  c #EC851C",
",  c #EC861D",
"<  c #ED8821",
"1  c #ED8A26",
"2  c #ED8B28",
"3  c #ED8C28",
"4  c #EE9132",
"5  c #EE9235",
"6  c #EE9336",
"7  c #EF953A",
"8  c #EF953B",
"9  c #F09C47",
"0  c #F1A557",
"q  c #F1A659",
"w  c #F2A85D",
"e  c #F2AA61",
"r  c #F2AD66",
"t  c #F3AF6A",
"y  c #F3B16D",
"u  c #225485",
"i  c #235485",
"p  c #235586",
"a  c #245586",
"s  c #245686",
"d  c #255686",
"f  c #265787",
"g  c #285988",
"h  c #295989",
"j  c #2A5A89",
"k  c #2B5B8A",
"l  c #2C5B8A",
"z  c #2C5C8B",
"x  c #34628F",
"c  c #366490",
"v  c #406B95",
"b  c #456F98",
"n  c #477199",
"m  c #557BA1",
"M  c #567CA2",
"N  c #6688AA",
"B  c #678AAB",
"V  c #7292B1",
"C  c #7695B3",
"Z  c #F6C18C",
"A  c #F6C28D",
"S  c #F7CC9F",
"D  c #F7CDA1",
"F  c #F7CDA2",
"G  c #F8CFA6",
"H  c #F8D1A9",
"J  c #F8D2AB",
"K  c #F8D3AC",
"L  c #F9D5B1",
"P  c #F9D8B7",
"I  c #FADCBE",
"U  c #FADDBF",
"Y  c #A2B7CB",
"T  c #A3B8CC",
"R  c #A5BACD",
"E  c #A9BCCF",
"W  c #ABBED1",
"Q  c #B7C8D7",
"!  c #BBCBDA",
"~  c #BDCCDB",
"^  c #BECCDB",
"/  c #BFCEDC",
"(  c #C3D1DF",
")  c #FADFC4",
"_  c #FBE2CA",
"`  c #FBE3CB",
"'  c #FCEAD9",
"]  c #FEEDDC",
"[  c #D3DDE7",
"{  c #D6E0EA",
"}  c #E1E8EF",
"|  c #FDF3E8",
" . c #FFF4E9",
".. c #FEF4EA",
"X. c #FEF5EC",
"o. c #E3EAF0",
"O. c #E4EAF0",
"+. c #E5EBF1",
"@. c #E7EEF4",
"#. c #F1F4F7",
"$. c #FFF9F3",
"%. c #FFFAF2",
"&. c #FFFBF5",
"*. c #FEFAF6",
"=. c #F2F5F8",
"-. c #FFFCF8",
";. c #FFFDFB",
":. c #F8FAFC",
">. c #FAFBFC",
",. c #FAFDFF",
"<. c #FBFDFF",
"1. c #FFFFFE",
"2. c #FFFFFF",
/* pixels */
"                                o o                             ",
"                              o o o o                           ",
"                                o o o o o                       ",
"                                  o o o o o                     ",
"                                    o o o o o                   ",
"                                      o o o o o                 ",
"          o o o o o o o o o o o o o o o o o o o o o             ",
"          o o o o o o o o o o o o o o o o o o o o o o           ",
"          o o o o o o o o o o o o o - 3 8 6 , o o o o o         ",
"                        o o o o - r I ..*.$.] S 8 o o o o       ",
"                      o o o o , K 2.<.{ ! ( @.2...t o o o o     ",
"                  o o o o o - H 2.O.C c g l n R <.$.0 o o o o   ",
"                o o o o o o q ;.=.B u d d d u z W 2._ : o o o   ",
"              o o o o o o o G 2.^ g d d d d d u M =.;.9 o o o   ",
"          o o o o o o o o * ) 2.T d d d d d d d v O.2.r o o o o ",
"        o o o o o o o o o % I 2.^ g d d d d d u m =.2.w o o o o ",
"      o o o o o o   o o o o A 2.#.N u d d d d g W 2.X.4 o o o o ",
"  o o o o o o       o o o o 6 | 2.} V x g g b Y :.2.D # o o o   ",
"  o o o o o         o o o o o y *.2.:.[ ! / O.2.2._ 1 o o o o   ",
"o o o o o             o o o o # e ' 2.2.2.2.2.*.H 3 o o o o o   ",
"  o o o               o o o o o o < t D P L A 9 % o o o o o     ",
"                        o o o o o o o o # # o o o o o o o       ",
"                          o o o o o o o o o o o o o o o         ",
"                            o o o o o o o o o o o o o           ",
"                                o o o o o o o o o               ",
"                                        o o                     "
};
