/* XPM */
static char *Blender_l[] = {
/* columns rows colors chars-per-pixel */
"48 39 156 2 ",
"   c None",
".  c #EA7400",
"X  c #EA7500",
"o  c #EA7600",
"O  c #EA7601",
"+  c #EA7701",
"@  c #EA7702",
"#  c #EA7803",
"$  c #EA7804",
"%  c #EA7906",
"&  c #EB7906",
"*  c #EB7A07",
"=  c #EB7A08",
"-  c #EB7C0A",
";  c #EB7C0C",
":  c #EB7D0C",
">  c #EC8013",
",  c #EC8014",
"<  c #EC8114",
"1  c #EC8216",
"2  c #EC8317",
"3  c #EC8318",
"4  c #EC841B",
"5  c #EC861E",
"6  c #ED861E",
"7  c #ED8923",
"8  c #ED8A25",
"9  c #ED8C29",
"0  c #EE8E2C",
"q  c #EE8E2D",
"w  c #EE9133",
"e  c #EE9234",
"r  c #EE9235",
"t  c #EF973D",
"y  c #EF9942",
"u  c #F09C47",
"i  c #F09E4B",
"p  c #F09F4B",
"a  c #F1A04F",
"s  c #F1A354",
"d  c #F2AC65",
"f  c #F3AE69",
"g  c #F3B371",
"h  c #F3B372",
"j  c #F4B97C",
"k  c #225485",
"l  c #235485",
"z  c #235585",
"x  c #235586",
"c  c #245586",
"v  c #255686",
"b  c #255687",
"n  c #265787",
"m  c #275787",
"M  c #295989",
"N  c #2A5A89",
"B  c #2D5C8B",
"V  c #2E5D8C",
"C  c #33618E",
"Z  c #386591",
"A  c #396691",
"S  c #3B6793",
"D  c #436D97",
"F  c #456F98",
"G  c #48719A",
"H  c #4B739B",
"J  c #4B749B",
"K  c #4B749C",
"L  c #537AA0",
"P  c #587EA3",
"I  c #597EA3",
"U  c #6789AB",
"Y  c #6A8CAD",
"T  c #7C99B6",
"R  c #7D9BB7",
"E  c #86A1BC",
"W  c #89A4BE",
"Q  c #F5BD84",
"!  c #F5BD85",
"~  c #F5BF88",
"^  c #F5C08A",
"/  c #F6C491",
"(  c #F7C899",
")  c #F7CA9C",
"_  c #F7CB9F",
"`  c #F7CC9F",
"'  c #F7CDA3",
"]  c #F8D0A8",
"[  c #F8D1A9",
"{  c #F8D2AA",
"}  c #F8D5B0",
"|  c #F9D5B1",
" . c #F9D7B5",
".. c #F9D8B7",
"X. c #F9D9B8",
"o. c #F9DAB9",
"O. c #F9DABB",
"+. c #91AAC2",
"@. c #98AFC6",
"#. c #9AB0C7",
"$. c #9DB3C9",
"%. c #A2B7CC",
"&. c #A4B8CC",
"*. c #A5B9CD",
"=. c #A8BCCF",
"-. c #ABBED1",
";. c #ADC0D2",
":. c #AEC0D2",
">. c #BCCBDA",
",. c #C5D2DF",
"<. c #FADFC4",
"1. c #FAE0C6",
"2. c #FAE2C8",
"3. c #FBE3CA",
"4. c #FBE6D0",
"5. c #FBE8D4",
"6. c #FCEEDF",
"7. c #D0DAE5",
"8. c #D4DEE7",
"9. c #D8E1EA",
"0. c #DAE3EB",
"q. c #DBE3EB",
"w. c #DCE4EC",
"e. c #E1E7EE",
"r. c #E2E9EF",
"t. c #FDF0E3",
"y. c #FDF1E5",
"u. c #FDF3E9",
"i. c #FDF4EB",
"p. c #FDF5EC",
"a. c #FEF6ED",
"s. c #FEF7EF",
"d. c #E6ECF1",
"f. c #E9EEF3",
"g. c #EBF0F4",
"h. c #ECF0F4",
"j. c #EEF2F6",
"k. c #FEF7F1",
"l. c #FEF9F3",
"z. c #FEF9F4",
"x. c #FEFAF6",
"c. c #F3F5F8",
"v. c #F5F7FA",
"b. c #F6F8FA",
"n. c #F7F9FB",
"m. c #F8F9FB",
"M. c #FEFBF8",
"N. c #FFFCF9",
"B. c #FFFDFB",
"V. c #FAFBFC",
"C. c #FBFCFD",
"Z. c #FCFDFD",
"A. c #FFFDFC",
"S. c #FDFEFE",
"D. c #FFFFFE",
"F. c #FFFFFF",
/* pixels */
"                                                o o                                             ",
"                                              o o o o o                                         ",
"                                              o o o o o o                                       ",
"                                              o o o o o o o                                     ",
"                                                o o o o o o o o                                 ",
"                                                  o o o o o o o o                               ",
"                                                      o o o o o o o                             ",
"                                                        o o o o o o o o                         ",
"                                                        o o o o o o o o o                       ",
"                o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o                     ",
"              o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o                 ",
"              o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o               ",
"                o o o o o o o o o o o o o o o o o o o o o o % % o o o o o o o o o o             ",
"                                    o o o o o o o o % r g _  .X.{ ! p > o o o o o o o           ",
"                                  o o o o o o o o t { a.F.F.F.F.F.F.M.2.d : o o o o o o         ",
"                                o o o o o o o % g i.F.F.F.V.j.g.v.F.F.F.F.{ 5 o o o o o o       ",
"                              o o o o o o o # j B.F.F.g.*.U K H P W 8.F.F.F.X.4 o o o o o o     ",
"                          o o o o o o o o o s z.F.F.7.P n k n n k k A %.C.F.F.( % o o o o o     ",
"                        o o o o o o o o o < 2.F.F.w.H k n n n n n n n B =.F.F.z.u o o o o o o   ",
"                      o o o o o o o o o o s B.F.F.R k n n n n n n n n n F r.F.F._ o o o o o o   ",
"                    o o o o o o o o o o o / F.F.d.D n n n n n n n n n n n :.F.F.5.< o o o o o   ",
"                o o o o o o o o o o o o % | F.F.8.C n n n n n n n n n n k +.F.F.u.9 o o o o o   ",
"              o o o o o o o o o o o o o % ..F.F.0.Z n n n n n n n n n n k #.F.F.a.0 o o o o o   ",
"            o o o o o o o o o o o o o o o ' F.F.c.P k n n n n n n n n n V ,.F.F.6.5 o o o o o o ",
"        o o o o o o o o o     o o o o o o g F.F.F.-.M n n n n n n n n k Y n.F.F...= o o o o o   ",
"      o o o o o o o o o       o o o o o o 0 y.F.F.m.E M k n n n n n k L 0.F.F.F.f o o o o o o   ",
"    o o o o o o o o o         o o o o o o o ~ F.F.F.n.&.H M n k n A R e.F.F.F.1.< o o o o o o   ",
"  o o o o o o o o o           o o o o o o o 3 X.F.F.F.F.f.>.$.@.:.0.F.F.F.F.y.y o o o o o o o   ",
"  o o o o o o o                 o o o o o o o 8 X.F.F.F.F.F.F.F.F.F.F.F.F.6.a o o o o o o o     ",
"  o o o o o o                   o o o o o o o o 3 ^ u.F.F.F.F.F.F.F.F.z.| r o o o o o o o o     ",
"  o o o o o                       o o o o o o o o o w ! <.t.a.k.u.4._ p - o o o o o o o o       ",
"      o                           o o o o o o o o o o o : 7 w r 9 > o o o o o o o o o o o       ",
"                                    o o o o o o o o o o o o o o o o o o o o o o o o o o         ",
"                                      o o o o o o o o o o o o o o o o o o o o o o o o           ",
"                                        o o o o o o o o o o o o o o o o o o o o o o             ",
"                                            o o o o o o o o o o o o o o o o o o                 ",
"                                                o o o o o o o o o o o o o o o                   ",
"                                                    o o o o o o o o o o                         ",
"                                                                                                "
};
