/* XPM */
static char *MSEdit_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 127 2 ",
"   c None",
".  c #2A8D55",
"X  c #2E945A",
"o  c #30965B",
"O  c #339C5E",
"+  c #319D62",
"@  c #36A263",
"#  c #39A564",
"$  c #3BAA66",
"%  c #39A668",
"&  c #3DAB6A",
"*  c #3FB069",
"=  c #41AE6D",
"-  c #42B36D",
";  c #45BA6F",
":  c #45B471",
">  c #48B672",
",  c #46BD71",
"<  c #4BBB75",
"1  c #4FBF78",
"2  c #50BF79",
"3  c #4AC374",
"4  c #4DC977",
"5  c #4ECB79",
"6  c #53C37B",
"7  c #55CA7D",
"8  c #58CA7F",
"9  c #53D17D",
"0  c #5CCD81",
"q  c #57D380",
"w  c #5DD383",
"e  c #62D486",
"r  c #64D788",
"t  c #66D98A",
"y  c #6ADC8D",
"u  c #6EDB91",
"i  c #73DD95",
"p  c #77DF98",
"a  c #78DF99",
"s  c #6DE18E",
"d  c #6FE390",
"f  c #71E591",
"g  c #76EA95",
"h  c #78EB97",
"j  c #7CE19C",
"k  c #7CEC9A",
"l  c #80E29F",
"z  c #81ED9E",
"x  c #84E4A2",
"c  c #8AE6A6",
"v  c #86EEA2",
"b  c #85EEA1",
"n  c #85EEA1",
"m  c #88EEA3",
"M  c #8AEEA4",
"N  c #8BEFA5",
"B  c #8DEFA7",
"V  c #8AEEA5",
"C  c #8CE7A8",
"Z  c #8DE7A8",
"A  c #8EE7A9",
"S  c #8EE7A9",
"D  c #8FE8AA",
"F  c #8FEFA8",
"G  c #90E8AA",
"H  c #91E8AB",
"J  c #90EFA9",
"K  c #91E8AC",
"L  c #93E9AD",
"P  c #94EAAE",
"I  c #95EAAE",
"U  c #96EAAF",
"Y  c #93E9AD",
"T  c #92F0AB",
"R  c #94F0AD",
"E  c #95F0AD",
"W  c #97F1AF",
"Q  c #94F0AD",
"!  c #98F1AF",
"~  c #97EBB0",
"^  c #98EBB0",
"/  c #99EBB1",
"(  c #99EBB2",
")  c #9BECB3",
"_  c #9DEDB4",
"`  c #9EEDB5",
"'  c #9CECB3",
"]  c #9AF1B1",
"[  c #9DF2B3",
"{  c #9FF2B5",
"}  c #9CF1B2",
"|  c #A0EEB6",
" . c #A0EEB7",
".. c #A1EEB7",
"X. c #A2EEB8",
"o. c #A2EFB8",
"O. c #A3EFB9",
"+. c #A3EFB9",
"@. c #A1F2B7",
"#. c #A1F2B6",
"$. c #A4F3B9",
"%. c #A5F0BA",
"&. c #A6F0BB",
"*. c #A4F3BA",
"=. c #A5F3BA",
"-. c #A6F3BA",
";. c #A7F0BC",
":. c #A7F3BC",
">. c #A5F2BA",
",. c #A8F1BD",
"<. c #A9F1BD",
"1. c #A8F3BC",
"2. c #A9F1BE",
"3. c #ABF2BE",
"4. c #ABF2BF",
"5. c #ACF2BF",
"6. c #A9F4BD",
"7. c #AAF4BE",
"8. c #ABF4BE",
"9. c #ACF4BF",
"0. c #AAF3BE",
"q. c #ACF2C0",
"w. c #ADF3C0",
"e. c #AEF3C1",
"r. c #ADF4C0",
"t. c #AEF4C1",
"y. c #ADF3C0",
/* pixels */
"                                                      *.q./ x                                   ",
"                                                    M 1.1.P j y                                 ",
"                                                  h J 9.O.D j t 9                               ",
"                                                  k ! t.| c p e 9                               ",
"                                                g z { q.) x i w 9                               ",
"                                                g v *.1.P l u q 9                               ",
"                                                h B 8.*.K j t 9 9                               ",
"                                                k E t.X.C p r 9 9                               ",
"                                              g k [ q._ c i w 9                                 ",
"                                              g v *.5./ x u q 9                                 ",
"                                    + +       g M 8.1.K j y 9 9                                 ",
"                                + + +         k T t.X.C a t 9 9                                 ",
"                            % @ + + +       g k ] t._ c p w 9                                   ",
"                        = & % # @ + +       g z @.q./ x u q 9       9 9                         ",
"                    > : - & & % @ @ +       g m 1.1.P l y q 9       7 5 4 3                     ",
"                2 < > : : = & % % @         h J 9.*.G j t 9 9       4 3 3 , , -                 ",
"            8 6 6 1 > > : - = & % #       g k E t.| c p e 9         3 , ; ; - * $ $             ",
"        w 0 8 6 6 6 < > : : - & % %       g z { q.) x i w 9       , ; - - * $ $ # @ O O         ",
"      e e 0 0 8 6 6 1 < > : - = & %       g v *.1.P l u q 9       - - & $ $ # @ O O o X #       ",
"    t r e w 0 8 6 6 6 < > > : - &         g B 8.;.K j t 9 9       & $ $ # @ O O o X . . - g     ",
"  s y t e e 0 0 8 6 6 6 < > : : =       g k E t.X.C a r 9         $ # @ O O X X . . o < y g g   ",
"f s y y t e e 0 0 8 6 6 < > > :         g k [ q._ c i w 9       @ @ O O X X . . o : e s f g g g ",
"f f s y t r e w 0 8 6 6 6 < >           g v $.5./ x u q 9         O X X . . o = 0 t y s d f g g ",
"g f s y y t e e 0 0 8 6 6               g M 8.1.K j y 9 9             . X = 6 w e t y y s f f g ",
"g f f s y y t e w 6 = X .             g h T t.O.C j t 9               6 6 8 0 0 e e t y y s f g ",
"g g f d s y t 0 = o . . X X O         g k ] t._ c p e 9           > < 6 6 6 8 0 w e r t y s f f ",
"g g g f s e > o . . X X O O @ @       g z @.q.) x i q 9         : > > 1 6 6 8 0 0 e e t y y s f ",
"  g g y < o . . X X O O @ # $         g m ;.1.P l y q 9       = : : > < 1 6 6 8 0 w e e t y s   ",
"    g - . . X o O O @ # $ $ &       g h F 8.*.G j t 9         & - : > > < 6 6 6 8 0 w e r t     ",
"      # X o O O @ # $ $ & - -       g k E t.| c p e 9       % & = - : > < 1 6 6 8 0 0 e e       ",
"        O O @ # $ $ * - - ; ,       g k { q.' x i w 9       % & & - : : > < 6 6 6 8 0 w         ",
"            $ $ * - - ; , 3         g v *.1.~ x u q 9       # % & = - : > > < 6 6 8             ",
"                - ; , 3 3 4       g g B 8.;.K j y 9         @ % % & = : : > < 1                 ",
"                    3 4 5 7       g k E t.X.C a r 9       + @ @ % & & - : >                     ",
"                        9 9       g k ] t._ c i w 9       + + @ # % & =                         ",
"                                  g z $.q./ x u q 9       + + + @ %                             ",
"                                  g M 8.1.P j y q         + + +                                 ",
"                                  h T t.O.C a t 9       + +                                     ",
"                                g k ] t._ c p e 9                                               ",
"                                  z @.q.) x i w                                                 ",
"                                  v *.1.P l y q                                                 ",
"                                  F 8.*.G j y                                                   ",
"                                  E t.| C p y                                                   ",
"                                  { q._ x p                                                     ",
"                                F *.1.~ x                                                       ",
"                                E 8.1.K l                                                       ",
"                                  t.X.C                                                         ",
"                                  q._ C                                                         "
};
