/* XPM */
static char *Natron_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 161 2 ",
"   c None",
".  c #000000",
"X  c #010101",
"o  c #020202",
"O  c #030303",
"+  c #060606",
"@  c #070707",
"#  c #090909",
"$  c #0A0A0A",
"%  c #0B0B0B",
"&  c #0C0C0C",
"*  c #0D0D0D",
"=  c #0E0E0E",
"-  c #0F0F0F",
";  c #111111",
":  c #121212",
">  c #131313",
",  c #141414",
"<  c #161616",
"1  c #171717",
"2  c #1A1A1A",
"3  c #1D1D1D",
"4  c #1F1F1F",
"5  c #202020",
"6  c #242424",
"7  c #262626",
"8  c #272727",
"9  c #292929",
"0  c #2F2F2F",
"q  c #303030",
"w  c #313131",
"e  c #323232",
"r  c #333333",
"t  c #343434",
"y  c #363636",
"u  c #3C3C3C",
"i  c #3D3D3D",
"p  c #3E3E3E",
"a  c #404040",
"s  c #424242",
"d  c #484848",
"f  c #4A4A4A",
"g  c #4D4D4D",
"h  c #4F4F4F",
"j  c #515151",
"k  c #525252",
"l  c #535353",
"z  c #545454",
"x  c #565656",
"c  c #585858",
"v  c #595959",
"b  c #5B5B5B",
"n  c #5E5E5E",
"m  c #636363",
"M  c #666666",
"N  c #696969",
"B  c #6E6E6E",
"V  c #707070",
"C  c #727272",
"Z  c #747474",
"A  c #767676",
"S  c #787878",
"D  c #7A7A7A",
"F  c #7D7D7D",
"G  c #7E7E7E",
"H  c #7F7F7F",
"J  c #808080",
"K  c #818181",
"L  c #828282",
"P  c #838383",
"I  c #848484",
"U  c #858585",
"Y  c #868686",
"T  c #878787",
"R  c #888888",
"E  c #8A8A8A",
"W  c #8B8B8B",
"Q  c #8D8D8D",
"!  c #8E8E8E",
"~  c #8F8F8F",
"^  c #919191",
"/  c #939393",
"(  c #949494",
")  c #969696",
"_  c #979797",
"`  c #989898",
"'  c #9A9A9A",
"]  c #9C9C9C",
"[  c #9D9D9D",
"{  c #9F9F9F",
"}  c #A0A0A0",
"|  c #A4A4A4",
" . c #A5A5A5",
".. c #A6A6A6",
"X. c #A7A7A7",
"o. c #A8A8A8",
"O. c #A9A9A9",
"+. c #AAAAAA",
"@. c #ABABAB",
"#. c #ADADAD",
"$. c #AEAEAE",
"%. c #AFAFAF",
"&. c #B0B0B0",
"*. c #B2B2B2",
"=. c #B4B4B4",
"-. c #B6B6B6",
";. c #B7B7B7",
":. c #B8B8B8",
">. c #B9B9B9",
",. c #BABABA",
"<. c #BDBDBD",
"1. c #BFBFBF",
"2. c #C1C1C1",
"3. c #C2C2C2",
"4. c #C3C3C3",
"5. c #C4C4C4",
"6. c #C6C6C6",
"7. c #C7C7C7",
"8. c #C8C8C8",
"9. c #CACACA",
"0. c #CCCCCC",
"q. c #CDCDCD",
"w. c #CECECE",
"e. c #CFCFCF",
"r. c #D2D2D2",
"t. c #D4D4D4",
"y. c #D5D5D5",
"u. c #D7D7D7",
"i. c #D9D9D9",
"p. c #DBDBDB",
"a. c #DCDCDC",
"s. c #DDDDDD",
"d. c #DEDEDE",
"f. c #DFDFDF",
"g. c #E0E0E0",
"h. c #E1E1E1",
"j. c #E3E3E3",
"k. c #E5E5E5",
"l. c #E6E6E6",
"z. c #E7E7E7",
"x. c #E8E8E8",
"c. c #ECECEC",
"v. c #EDEDED",
"b. c #EEEEEE",
"n. c #EFEFEF",
"m. c #F0F0F0",
"M. c #F1F1F1",
"N. c #F2F2F2",
"B. c #F3F3F3",
"V. c #F4F4F4",
"C. c #F5F5F5",
"Z. c #F6F6F6",
"A. c #F7F7F7",
"S. c #F8F8F8",
"D. c #F9F9F9",
"F. c #FAFAFA",
"G. c #FBFBFB",
"H. c #FCFCFC",
"J. c #FDFDFD",
"K. c #FEFEFE",
"L. c #FFFFFF",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                          F F F F F F F F F F F F F F F F F F F F F F                           ",
"                      F ~ >.9.9.5.5.9.9.9.5.5.5.9.9.5.5.5.5.5.5.5.5.=.~ F                       ",
"                      ~ j.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.f.~                       ",
"                    L 5.L.c.+. . . . . . . . . . . . . . . . . . .$.c.L.2.L                     ",
"                  F ] A.L.D . . . . . . . . . . . . . . . . . . . . L L.N.` F                   ",
"                  T t.L.9.< . . . . . . . . . . . . . . . . . . . . 2 0.L.r.T                   ",
"                F +.L.S.c . . . . . . . . . . . . . . . . . . . . . . n S.S.+.F                 ",
"                W j.L.$.# . . * N  .+.+.+.+. .Z < . . . . . . < < . . # &.L.j.W                 ",
"              F >.L.c.u . . . T L.L.L.L.L.L.L.L.] @ . . . . . t F . . . s c.L.=.F               ",
"              ( c.L.~ . . . u c.L.L.L.L.L.L.L.L.A.j . . . . . r f.u . . . ^ L.c.^               ",
"            L 9.L.i.6 . . # $.L.L.L.L.L.L.L.L.L.L.2.: . . . . r N.$.# . . 6 f.L.9.L             ",
"          F } A.L.B . . . c S.L.L.L.L.L.L.L.L.L.L.L.V . . . . r N.S.c . . . V L.A.] F           ",
"          T i.L.2.: . . < 9.L.L.L.L.L.L.L.L.L.L.L.L.i.6 . . . r c.L.9.< . . < 5.L.t.T           ",
"        F $.L.A.g . . . Z L.L.L.L.L.L.L.L.L.L.L.L.L.L.^ . . . r c.L.L.Z . . . j A.L.$.F         ",
"        ~ z.L. .@ . . 9 f.L.L.L.L.L.L.L.L.L.L.L.L.L.L.c.u . . r c.L.L.f.9 . . # +.L.z.~         ",
"      F 1.L.z.r . . . ( L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.&.# . r c.L.L.L.( . . . t x.L.1.F       ",
"      ` N.L.T . . . s c.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.S.c . r c.L.L.L.N.s . . . T L.N.(       ",
"    L 0.L.r.3 . . * =.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.0.< r c.L.L.L.L.=.* . . 3 t.L.0.L     ",
"  F  .S.S.m . . . n S.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.D r c.L.L.L.L.S.n . . . M L.S. .F   ",
"  W f.L.=.* . . 2 0.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.f.N c.L.L.L.L.L.0.2 . . * >.L.f.W   ",
"  ] S.A.d . . . x L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.c.L.L.L.L.L.L.L.x . . . d A.S.]   ",
"  ] S.A.d . . . x L.L.L.L.L.L.S.i.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.j . . . d A.S.]   ",
"  W f.L.>.* . . 2 0.L.L.L.L.L.c.x r.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.0.2 . . * =.L.f.W   ",
"  F } S.L.M . . . n S.L.L.L.L.c.0 M L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.S.n . . . m S.S. .F   ",
"    L 0.L.t.3 . . * =.L.L.L.L.c.r * 1.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.=.* . . 3 r.L.0.L     ",
"      ( N.L.T . . . s c.L.L.L.c.r . g A.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.c.s . . . T L.N.`       ",
"      F 1.L.x.t . . . ( L.L.L.c.r . @  .L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.( . . . r z.L.1.F       ",
"        ~ z.L. .@ . . 9 f.L.L.c.r . . t z.L.L.L.L.L.L.L.L.L.L.L.L.L.L.f.9 . . @  .L.z.~         ",
"        F $.L.A.j . . . Z L.L.c.r . . . T L.L.L.L.L.L.L.L.L.L.L.L.L.L.Z . . . g A.L.$.F         ",
"          T i.L.5.< . . < 9.L.c.r . . . 5 t.L.L.L.L.L.L.L.L.L.L.L.L.9.< . . : 2.L.i.T           ",
"          F ] A.L.V . . . c S.N.r . . . . N L.L.L.L.L.L.L.L.L.L.L.S.c . . . B L.A.} F           ",
"            L 9.L.f.6 . . # $.N.r . . . . : 1.L.L.L.L.L.L.L.L.L.L.$.# . . 6 i.L.9.L             ",
"              ^ c.L.^ . . . u f.r . . . . . g A.L.L.L.L.L.L.L.L.c.u . . . ~ L.c.(               ",
"              F =.L.c.s . . . F t . . . . . @ ` L.L.L.L.L.L.L.L.T . . . u c.L.>.F               ",
"                W j.L.&.# . . < < . . . . . . : V  .+.+.+.+. .N * . . # $.L.j.W                 ",
"                F +.S.S.n . . . . . . . . . . . . . . . . . . . . . . c S.L.+.F                 ",
"                  T r.L.0.2 . . . . . . . . . . . . . . . . . . . . < 9.L.t.T                   ",
"                  F ` N.L.L . . . . . . . . . . . . . . . . . . . . D L.A.] F                   ",
"                    L 2.L.c.$. . . . . . . . . . . . . . . . . . .+.x.L.5.L                     ",
"                      ~ f.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.j.~                       ",
"                      F ~ =.5.5.5.5.5.5.9.5.9.9.9.9.5.5.5.9.9.9.9.9.>.~ F                       ",
"                          F F F F F F F F F F F F F F F F F F F F F F                           ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
