/* XPM */
static char *Seahorse_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 122 2 ",
"   c None",
".  c #221B2E",
"X  c #241E31",
"o  c #252333",
"O  c #252936",
"+  c #332E3E",
"@  c #22373B",
"#  c #263A3E",
"$  c #3D3848",
"%  c #264141",
"&  c #297459",
"*  c #2A785B",
"=  c #504A59",
"-  c #55515E",
";  c #595462",
":  c #6C787A",
">  c #76727D",
",  c #79747E",
"<  c #398166",
"1  c #26A369",
"2  c #27AC6F",
"3  c #28AB6F",
"4  c #29AE71",
"5  c #32AE76",
"6  c #34AF78",
"7  c #26B171",
"8  c #2AB374",
"9  c #2BB877",
"0  c #2DB578",
"q  c #2DBD7B",
"w  c #33B479",
"e  c #4A9A77",
"r  c #2EC27E",
"t  c #31C37F",
"y  c #689785",
"u  c #40B780",
"i  c #43BA83",
"p  c #49BA86",
"a  c #5DBA8E",
"s  c #5FB990",
"d  c #68AB8D",
"f  c #34C581",
"g  c #38C782",
"h  c #3DC984",
"j  c #3FC688",
"k  c #42CC86",
"l  c #47C68A",
"z  c #4FC08C",
"x  c #48CE88",
"c  c #4DD18A",
"v  c #52D38C",
"b  c #5AD78F",
"n  c #4ECA91",
"m  c #5BCE99",
"M  c #5DD991",
"N  c #62C294",
"B  c #6BC199",
"V  c #64CF9E",
"C  c #63DB93",
"Z  c #69DE95",
"A  c #64D09E",
"S  c #72E299",
"D  c #79E69B",
"F  c #6EC8A0",
"G  c #7BC2A1",
"H  c #7ECAA7",
"J  c #6DD2A3",
"K  c #75D3A3",
"L  c #7DD3AB",
"P  c #879193",
"I  c #939296",
"U  c #80A095",
"Y  c #87A59B",
"T  c #A19EA5",
"R  c #9CAFA8",
"E  c #80BBA0",
"W  c #99BAAB",
"Q  c #A1B1AB",
"!  c #BAB9BB",
"~  c #93C1AC",
"^  c #8FD7A8",
"/  c #88D1B0",
"(  c #9ADDBD",
")  c #A2C8B5",
"_  c #B7C7BF",
"`  c #B4CCC0",
"'  c #B1E3CB",
"]  c #C3C4C5",
"[  c #CECCCB",
"{  c #C2D7CC",
"}  c #CCD7D3",
"|  c #CEDCD4",
" . c #D5D4D3",
".. c #D8D7D8",
"X. c #DDDCDC",
"o. c #E0DFDD",
"O. c #C3E4D5",
"+. c #D1ECDE",
"@. c #DDE2E0",
"#. c #E4E3E3",
"$. c #E8E7E5",
"%. c #EBEDEA",
"&. c #F1EFEE",
"*. c #E1F0E8",
"=. c #EEF1EF",
"-. c #F0F0EF",
";. c #EFF3F0",
":. c #F7F6F5",
">. c #F7F6F4",
",. c #F6F5F4",
"<. c #F4F3F2",
"1. c #F8F5F5",
"2. c #F8F6F5",
"3. c #F8F7F6",
"4. c #F8F7F7",
"5. c #F9F8F7",
"6. c #FAF9F8",
"7. c #FAF9F9",
"8. c #FAFAF9",
"9. c #FBFAF9",
"0. c #FBFAFA",
"q. c #FBFAF9",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                            >.>.>.>.>.>.>.>.                                                    ",
"                          >.>.>.>.>.>.>.>.>.>.                                                  ",
"                        >.>.>.>.>.>.,.>.>.>.>.>.                                                ",
"                      >.>.>.>.>.#.Q R X.>.>.>.>.>.                                              ",
"                r r ( >.>.>.>.>.~ w w E <.>.>.>.2.' f r r r r r r r r r r r r r                 ",
"              r r j +.2.>.>.>.,.L r r V =.>.>.>.>.*.n r r r r r r r r r r r r r                 ",
"              r r m =.>.>.>.>.>.+.J A O.>.>.>.>.>.<.K r r r r r r r r r r r r r r               ",
"              0 8 B <.>.>.>.>.>.>.<.=.>.>.>.>.>.>.2.^ 8 0 0 0 0 0 0 0 0 0 0 0 0 0               ",
"              # @ : <.>.>.>.>.>.>.>.>.>.>.>.>.>.>.2.P @ # # # # # # # # # # # # %               ",
"              o . ; %.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.> . X X X X X X X X X X X X O               ",
"              o X $ ..2.>.>.>.>.>.>.>.>.>.>.>.>.>.%.- . X X X X X X X X X X X X O               ",
"              o X o T 5.>.>.>.>.>.>.>.>.>.>.>.>.5.] + X X X X X X X X o X X X X O               ",
"              o X . = X.2.>.>.>.>.>.>.>.>.>.>.>.&., . X X X X X X X X X X X X X O               ",
"              & & & & U %.2.>.>.>.>.>.>.>.>.>.,.` < & & & & & & & & & & & & & & *               ",
"              r r r r 6 Y #.2.>.>.>.>.>.>.>.<.{ z r r r r r r r r r r r r r r r r               ",
"              r r r r r 5 y ] >.>.>.>.>.<.%.) p r r q q q q r q q q q q q r r r r               ",
"              r r r q q 8 2 d <.>.>.2.>.X.| p 1 8 8 8 8 8 4 8 8 1 8 8 8 8 q r r r               ",
"              r r 9 3 9 8 7 s %.$.,.6.>. .| i 1 8 8 8 8 8 3 8 8 1 8 8 8 8 q r r r               ",
"              r r 8 1 9 8 7 s %.X.,.6.>.[ _ u 1 8 8 8 8 8 3 8 8 1 8 8 8 8 q r r r               ",
"              r r r 8 q 8 7 a %.o.,.6.>.W e 8 1 8 8 8 8 8 3 8 8 1 8 8 8 8 q r r r               ",
"              r r r r r 9 8 N %.o.,.6.,.G 7 9 4 9 9 9 9 8 8 9 9 4 9 9 9 9 r r r r               ",
"              r r r r r r r V %.o.,.6.%.B r r r r r r r r r r r r r r r r r r r r               ",
"              r r r r r r r V %.o.,.6.,.H r r r r r r r r r r r r r r r r r r r r               ",
"              r r r r k f r V %.o.,.6.@.a k r r r g k r r r h h r r r k f r r r r               ",
"              r r t v Z b h V %.o.,.6.%.K Z v f k C C c t c C C x t v Z b k r r r               ",
"              r r t b D S k V %.o.,.6.=.^ D C f k S D v t c S S c t b D S k r r r               ",
"              r r t v Z M h V %.o.,.6.} N Z v f k M Z c t c C C x t v Z M k r r r               ",
"              r r r r k f r V %.o.,.6.O.l k r r r g h r r r h g r r r k f r r r r               ",
"              r r r r r r r V %.o.,.6.=.N r r r r r r r r r r r r r r r r r r r                 ",
"                r r r r r r V %.o.,.6.%.N r r r r r r r r r r r r r r r r r r r                 ",
"                            ( %.o.>.-.!                                                         ",
"                               . .#.!                                                           ",
"                                I I                                                             ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
