/* XPM */
static char *Waterfox_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 160 2 ",
"   c None",
".  c #357FEC",
"X  c #3C7BEC",
"o  c #437DEC",
"O  c #487FED",
"+  c #0095EB",
"@  c #019BEC",
"#  c #089DF4",
"$  c #3680ED",
"%  c #3A83EE",
"&  c #3289EF",
"*  c #2A97F2",
"=  c #259FF3",
"-  c #01A3EC",
";  c #02ACEC",
":  c #03B3EC",
">  c #04BBEC",
",  c #09A4F6",
"<  c #0AABF6",
"1  c #08A6F8",
"2  c #09ACF9",
"3  c #1FAEF6",
"4  c #0BB2F5",
"5  c #0EBCF4",
"6  c #09B4FA",
"7  c #0ABBFB",
"8  c #10B6F7",
"9  c #1AB1F7",
"0  c #11BAF7",
"q  c #13BCF8",
"w  c #24A7F5",
"e  c #2AA0F4",
"r  c #21B3F7",
"t  c #4C81ED",
"y  c #5484EE",
"u  c #5A87EF",
"i  c #5D88EF",
"p  c #5F88F0",
"a  c #638AF0",
"s  c #6C8DF1",
"d  c #708FF1",
"f  c #7491F2",
"g  c #7A93F3",
"h  c #05C4EC",
"j  c #06CCEB",
"k  c #07D2EB",
"l  c #08D2EC",
"z  c #0BC4FC",
"x  c #0CCBFD",
"c  c #11C5F6",
"v  c #14C4F9",
"b  c #19C2FA",
"n  c #15CBFA",
"m  c #19CDFB",
"M  c #0DD3FE",
"N  c #16D4FB",
"B  c #1BD4FB",
"V  c #17D9FC",
"C  c #1ADDFC",
"Z  c #20D5FC",
"A  c #21DBFC",
"S  c #2ADCFC",
"D  c #0CE4FF",
"F  c #10E5FF",
"G  c #1BE4FD",
"H  c #1EEAFE",
"J  c #22E2FD",
"K  c #21EEFF",
"L  c #2CEDFE",
"P  c #39E9FE",
"I  c #25F1FF",
"U  c #2AF2FF",
"Y  c #30F3FF",
"T  c #3CF3FE",
"R  c #4BE3FC",
"E  c #46EAFF",
"W  c #4AEAFF",
"Q  c #52ECFF",
"!  c #5CEDFF",
"~  c #40F3FD",
"^  c #4CF6FD",
"/  c #50F6FF",
"(  c #58F6FF",
")  c #52F8FD",
"_  c #5CFBFC",
"`  c #66EFFF",
"'  c #6EE8FE",
"]  c #79E4FC",
"[  c #72E9FE",
"{  c #7DEBFE",
"}  c #62F4FE",
"|  c #6CF0FF",
" . c #6AF8FF",
".. c #74F1FF",
"X. c #7CF2FF",
"o. c #71F8FF",
"O. c #84ECFE",
"+. c #93EEFE",
"@. c #98EFFE",
"#. c #85F4FF",
"$. c #8BF5FE",
"%. c #8EFBFE",
"&. c #95F6FE",
"*. c #9CF5FE",
"=. c #90FBFE",
"-. c #A7E8FB",
";. c #ADEAFC",
":. c #ABEDFC",
">. c #AFECFC",
",. c #B1ECFC",
"<. c #B4EFFD",
"1. c #A1F0FE",
"2. c #A6F1FE",
"3. c #ADFDFE",
"4. c #AFFDFE",
"5. c #B6F0FD",
"6. c #B9F1FD",
"7. c #B9F2FD",
"8. c #BAF4FD",
"9. c #BDF4FD",
"0. c #BDF5FD",
"q. c #BDF6FD",
"w. c #BEF6FD",
"e. c #B1FDFE",
"r. c #B4FDFE",
"t. c #B5FDFE",
"y. c #B7FEFE",
"u. c #B9FDFE",
"i. c #B9FEFE",
"p. c #BBFEFE",
"a. c #BDFEFE",
"s. c #BEFEFE",
"d. c #C0F6FD",
"f. c #C0F7FD",
"g. c #C2F7FE",
"h. c #C0F6FE",
"j. c #C2F8FD",
"k. c #C3F8FE",
"l. c #C4F8FE",
"z. c #C4F9FE",
"x. c #C5FAFE",
"c. c #C0FEFE",
"v. c #C1FEFE",
"b. c #C1FFFE",
"n. c #C2FEFE",
"m. c #C3FEFE",
"M. c #C4FEFE",
"N. c #C5FEFE",
"B. c #C4FFFE",
"V. c #C7FEFE",
"C. c #C7FFFE",
"Z. c #C6FFFE",
"A. c #C8FDFE",
"S. c #C8FCFE",
"D. c #C8FEFE",
"F. c #C8FFFE",
"G. c #C9FFFE",
"H. c #C9FEFE",
"J. c #CAFFFE",
"K. c #CBFFFE",
/* pixels */
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                  1.2.                          ",
"                                                                O.+.@.+.                        ",
"                                            &.*.*.*.*.          { { O.{                         ",
"                                          #.&.&.&.&.&.&.        [ [ [ [                         ",
"                                        ..X.#.$.$.$.$.#.          ' '                           ",
"                                      ! ` | ..X.X.X.X...                                        ",
"                                      Q ! ! ` | | | | `                                         ",
"                                    E W Q Q ! ! ! ! !                                           ",
"                                    E E E W W Q Q Q                                             ",
"                                    E E E E E                                                   ",
"                          _ _ )     E E E E           e.t.u.a.c.c.N.D.                          ",
"                        / / ^ ^     E E           4.t.u.a.c.N.D.D.D.D.D.                        ",
"      l j j j h         T ~ T T                 4.t.a.c.N.D.D.D.x.f.j.x.        f f g g g       ",
"  l l k j j h h >       L L L L             T =.u.c.N.N.D.D.x.q.q.f.j.x.      s f f g g g g g   ",
"  l l j j h h h > >     H H H             U / t.c.N.D.D.D.f.5.6.q.f.j.      s s d f f f g g g   ",
"l j j j h h h > > >       F D           U U  .c.N.N.D.D.q.,.<.6.q.f.        a s s d f f f f f f ",
"j j j h h h > > > : :       D           U U o.N.N.D.D.q.;.,.5.8.          a a s s s s d d f d d ",
"j h h h h > > > : : :                 U U U ( c.D.N.$.] -.:.*.*.          i a a a s s s s s s s ",
"h h h > > > : : : ; ;               U U U U Y o.%.} S S R E P             u i a a a s s s s s s ",
"  > > > > : : : ; ; ; ;             U U U U U U U J Z A J B             y y u i a a a a a a a   ",
"  > > : : : : ; ; ; ; -           I I I I U U I J Z A A A 4 <           y y y u u i p a a a p   ",
"    : : : ; ; ; ; - - - -         I I I I I I K Z B A J q , 4 7       t t y y y y u u u u u     ",
"    ; ; ; ; ; - - - - - -       I I I I I I I A B A J m , < 6 z       t t t t y y y y y y y     ",
"    ; ; ; - - - - - - - @ @   I I I I I I I J B B A C < , 4 7 z x   o o O t t t t y y y y y     ",
"      - - - - - - @ @ @ @ @   I I I I I I K B B C J q , < 6 z x M r o o o o O t t t t t t       ",
"      - - - - @ @ @ @ @ @ @ N I K K I I I C m B C B , , 4 7 z x M b % o o o o o O t t t t       ",
"        @ @ @ @ @ @ @ @ @ 4 K K K K K K J m B C C 8 # < 6 z x M M M e X o o o o o o o o         ",
"        @ @ @ @ @ @ @ + @ V K H H H K K B m B C m # , 2 7 z x M M M v % X X X o o o o o         ",
"          @ @ @ + + + + 5 H H H H H H C m B C C < # , 4 7 x M M M M M w X X X X X X X           ",
"          + + + + + + - C H H H H H G m m B C C # , < 6 7 x M M M M M n & X X X X X X           ",
"            + + + + + c G G G G H H V m m N C     , 4 6 7 z x M M M M M 3 X X X X X             ",
"            < @ + @ 4 G G G G G G G n n B V C     2 4 7 7 7 x M M M M M x = . X $ *             ",
"            C N c N C G G G G G G N v n B V         6 7 7 7 7 x x x x x x x q 9 q x             ",
"              C C C C C C C C C N v v n V             7 7 7 7 z x x x x x x x x x               ",
"              V V V V V V V V V v v v n N             7 7 7 6 6 z x x x x z z z z               ",
"                N N N N N N N n q v n n                 6 6 4 4 4 z z z z z z z                 ",
"                n n n n n n v q q v n n                 6 4 4 2 2 4 6 7 7 7 7 7                 ",
"                  v v v v q 0 0 q v v                     2 2 2 2 2 2 4 4 6 7                   ",
"                  v v q q q 0 0 q v v                     2 1 1 1 1 2 2 4 4 6                   ",
"                    q q 0 0 0 0 q v                         1 1 1 1 1 2 2 4                     ",
"                      0 8 8 0 0 q                             1 1 1 1 1 2                       ",
"                          8 0                                     1 1                           ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
