/* XPM */
static char *Waterfox_m[] = {
/* columns rows colors chars-per-pixel */
"32 32 122 2 ",
"   c None",
".  c #3C7BEC",
"X  c #447EED",
"o  c #0095EB",
"O  c #019CEC",
"+  c #3684EE",
"@  c #3C82ED",
"#  c #01A3EC",
"$  c #02ABEC",
"%  c #03B4EC",
"&  c #04BCEC",
"*  c #09A5F6",
"=  c #09ABF6",
"-  c #08A7F8",
";  c #09ACF9",
":  c #1CAFF7",
">  c #0DB3F5",
",  c #0DBBF4",
"<  c #0AB4F9",
"1  c #0ABAFB",
"2  c #11B7F6",
"3  c #1BB1F7",
"4  c #11BAF7",
"5  c #12BBF8",
"6  c #22A5F5",
"7  c #2AA1F4",
"8  c #4C81ED",
"9  c #5484EE",
"0  c #5A86EF",
"q  c #5E88EF",
"w  c #638AF0",
"e  c #6C8EF1",
"r  c #7491F2",
"t  c #7A93F3",
"y  c #05C4EC",
"u  c #06CBEB",
"i  c #07D2EB",
"p  c #08D4EB",
"a  c #0BC4FC",
"s  c #0CCCFD",
"d  c #11C5F6",
"f  c #14C3F9",
"g  c #1AC0FA",
"h  c #14CAF9",
"j  c #18CDFB",
"k  c #0DD3FE",
"l  c #17D4FB",
"z  c #1CD3FB",
"x  c #1ADBFC",
"c  c #20D7FC",
"v  c #21DEFD",
"b  c #32DDFC",
"n  c #0EE5FF",
"m  c #1BE4FD",
"M  c #1FEBFE",
"N  c #21E2FD",
"B  c #22EDFF",
"V  c #36E1FD",
"C  c #25F1FF",
"Z  c #29F2FF",
"A  c #35F3FE",
"S  c #3AF2FE",
"D  c #41E3FD",
"F  c #46EAFF",
"G  c #4BEBFF",
"H  c #54ECFF",
"J  c #5EEEFF",
"K  c #4BF6FD",
"L  c #50F5FF",
"P  c #52F8FD",
"I  c #66EFFF",
"U  c #68EFFF",
"Y  c #71E9FE",
"T  c #7BEAFE",
"R  c #68F6FE",
"E  c #73F1FF",
"W  c #7CF2FF",
"Q  c #76F9FE",
"!  c #86ECFE",
"~  c #93E9FC",
"^  c #84F3FF",
"/  c #8CF5FE",
"(  c #8FFBFE",
")  c #95F6FE",
"_  c #92F6FE",
"`  c #9DF0FE",
"'  c #9BF7FE",
"]  c #9CF7FE",
"[  c #9EF7FE",
"{  c #A7EBFC",
"}  c #B4EEFC",
"|  c #A4F1FD",
" . c #A6F9FE",
".. c #A4FCFE",
"X. c #ABFDFE",
"o. c #B6F0FD",
"O. c #BBF2FD",
"+. c #BCF3FD",
"@. c #BCF5FD",
"#. c #B2FDFE",
"$. c #B3FDFE",
"%. c #B9FDFE",
"&. c #BBFDFE",
"*. c #BEFEFE",
"=. c #BFFEFE",
"-. c #C0F7FE",
";. c #C2F7FE",
":. c #C3F8FE",
">. c #C3FAFE",
",. c #C4F9FE",
"<. c #C5FBFE",
"1. c #C2FEFE",
"2. c #C7FDFE",
"3. c #C4FEFE",
"4. c #C6FEFE",
"5. c #C7FEFE",
"6. c #C7FFFE",
"7. c #C8FCFE",
"8. c #C8FDFE",
"9. c #C8FFFE",
"0. c #C9FFFE",
"q. c #CAFFFE",
/* pixels */
"                                                                ",
"                                                                ",
"                                            `                   ",
"                              ' [ ]       T ! !                 ",
"                            ^ _ ) _ /     Y Y Y                 ",
"                          I E W ^ W W                           ",
"                        G H J I U I I                           ",
"                        G G G H H                               ",
"                        F F G           %.*.                    ",
"                P P K   F F       #.%.*.6.6.6.9.                ",
"  p i u y       S S A         Q #.*.6.9.9.>.;.<.      r t t t   ",
"i i u u y &     B M         A ( 1.6.9.<.O.+.;.      e r r t t t ",
"u u u y & & %     n       Z S X.6.9.>.} o.@.      w e e r r r r ",
"u y y & & % %             Z A ..9. .~ { |         w w e e e e e ",
"y y & & % % $ $         Z Z Z L R V b D         0 q w w w e e w ",
"  & % % % $ $ $         Z Z Z C N c v h =       9 9 0 q w w w   ",
"  % % $ $ $ $ $ #     C C C C B z v z = <     8 8 9 9 9 0 0 0   ",
"    $ $ $ $ # # O   C C C C B x z x > = 1 s   X 8 8 8 9 9 9     ",
"    # # # O O O O , C C C C N z x f * < a k 7 X X X 8 8 8 8     ",
"    O O O O O O O l B B B B z z z * = 1 s k g @ X X X X X X     ",
"      O O O o o > M M M M x z x 4 * < a s k k 7 . . X X X       ",
"      o o o o O x M M M m j z x * = < a k k k h + . . . .       ",
"        O o o , m m m m z j x     ; 1 a s k k k 6 . . .         ",
"        d , d x m m m x h l x     < 1 1 a s s s s : 6 3         ",
"          x x x x x x h h l         1 1 1 a s s s s s           ",
"          l l l l l h f h l         1 < < < a a a a a           ",
"            h h h f 5 f h             < ; ; < < 1 1             ",
"            f f 5 5 5 f               ; - - ; ; < <             ",
"              5 5 5 5 f                 - - - ; ;               ",
"                2 5                         - -                 ",
"                                                                ",
"                                                                "
};
